name: mysphereclean
description: MySphere profil yönetim uygulaması.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase paketleri
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0

  # Fotoğraf seçmek için
  image_picker: ^1.1.1

  # Link açma
  url_launcher: ^6.3.0

  # QR kod
  qr_flutter: ^4.1.0

  # Paylaşım
  share_plus: ^10.0.0

  # Tema / oturum saklama
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
